"""added resume table

Revision ID: c03aa55ec574
Revises: 998a2e8da3e4
Create Date: 2024-11-29 19:54:10.030306

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c03aa55ec574"
down_revision: Union[str, None] = "998a2e8da3e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('resume_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("link", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="resume_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="resume_pkey"),
        postgresql_ignore_search_path=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume")
    # ### end Alembic commands ###
