"""Add Certification table

Revision ID: cbedca6e70ce
Revises: 2c2dec35fe1a
Create Date: 2024-12-02 21:33:19.660761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbedca6e70ce"
down_revision: Union[str, None] = "2c2dec35fe1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("issuing_organization", sa.String(length=255), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("credential_id", sa.String(length=255), nullable=False),
        sa.Column("credential_url", sa.String(length=255), nullable=False),
        sa.Column("skills_acquired", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "images", "url", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "images", "url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_table("certifications")
    # ### end Alembic commands ###
