"""Updated Project model, added Image model for storing images

Revision ID: 03e35137dc5d
Revises: 2468a4d1f398
Create Date: 2024-11-10 23:17:52.413877

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03e35137dc5d"
down_revision = "2468a4d1f398"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.project_id"],
        ),
        sa.PrimaryKeyConstraint("image_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("images")
    # ### end Alembic commands ###
