"""added tech_stack field into projects model

Revision ID: 2baab3c46fce
Revises: 1b858221a19b
Create Date: 2024-11-14 23:51:57.231188

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2baab3c46fce"
down_revision = "1b858221a19b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tech_stack", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("tech_stack")

    # ### end Alembic commands ###
