"""added project categories table

Revision ID: f16749a74f3b
Revises: 2baab3c46fce
Create Date: 2024-11-15 00:12:50.066209

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f16749a74f3b"
down_revision = "2baab3c46fce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("project_category_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            None, "project_categories", ["project_category_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("project_category_id")

    op.drop_table("project_categories")
    # ### end Alembic commands ###
